name: sisters_directory
description: Sisters Directory - UFS Mangalore Province management app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
 

  # State management
  provider: ^6.1.2

  # UI
  fl_chart: ^0.69.0
  table_calendar: ^3.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  

  # Misc
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  pdf: ^3.13.0
  printing: ^5.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/jesus_calling.png
    - assets/images/logo.png
