// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEZOLrC7mpIByQ5vhQZtJjUsnHhgb4yKQ',
    appId: '1:636442659269:web:7cf4f3fb9e6ab98d66a3ac',
    messagingSenderId: '636442659269',
    projectId: 'sisters-directory',
    authDomain: 'sisters-directory.firebaseapp.com',
    storageBucket: 'sisters-directory.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgAVdP-jUi0YZpe12U-06e8zpze8FFkM',
    appId: '1:636442659269:android:93e4ef2b0a0e143666a3ac',
    messagingSenderId: '636442659269',
    projectId: 'sisters-directory',
    storageBucket: 'sisters-directory.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLHO0_XWas1WZxAONtnuJW6Dv6wm-sgTs',
    appId: '1:636442659269:ios:a8fbff9758a8e7cf66a3ac',
    messagingSenderId: '636442659269',
    projectId: 'sisters-directory',
    storageBucket: 'sisters-directory.firebasestorage.app',
    iosBundleId: 'com.example.sistersDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEZOLrC7mpIByQ5vhQZtJjUsnHhgb4yKQ',
    appId: '1:636442659269:web:1e0fb63d6eb168ca66a3ac',
    messagingSenderId: '636442659269',
    projectId: 'sisters-directory',
    authDomain: 'sisters-directory.firebaseapp.com',
    storageBucket: 'sisters-directory.firebasestorage.app',
  );
}
